title: Brian's Qubes Cookbook
description: Brian's recipes for Qubes OS
theme: just-the-docs
timezone: America/New_York

strict_front_matter: true

url: https://bcduggan.github.io/brians-qubes-cookbook

aux_links:
  Brian's Qubes Cookbook on GitHub: https://github.com/bcduggan/brians-qubes-cookbook

#color_scheme: dark

callouts_opacity: 0.5
callouts:
  white:
    color: white
    opacity: 1
  black:
    color: grey-dk
  purple:
    color: purple
  blue:
    color: blue
  gray:
    color: grey-lt
  green:
    color: green
  yellow:
    color: yellow
  orange:
    color: orange
  red:
    color: red
