title: Brian's Qubes Cookbook
description: Brian's recipes for Qubes OS
theme: just-the-docs

url: https://bcduggan.github.io/brians-qubes-cookbook

aux_links:
  Template Repository: https://github.com/bcduggan/brians-qubes-cookbook
