title: Brian's Qubes Cookbook
description: Brian's recipes for Qubes OS
theme: just-the-docs
timezone: America/New_York

strict_front_matter: true

url: https://bcduggan.github.io/brians-qubes-cookbook

aux_links:
  Template Repository: https://github.com/bcduggan/brians-qubes-cookbook

qubes_namespace: brian
qubes_user: user

collections:
  conventions:
    permalink: "/:collection/:path"
    output: true
  recipes:
    permalink: "/:collection/:path"
    output: true

just_the_docs:
  collections:
    conventions:
      name: "Conventions"
    recipes:
      name: "Recipes"
