services:
  jekyll:
    build:
      context: "."
      dockerfile_inline: |
        FROM ruby:3.3-bookworm
        EXPOSE 4000
        WORKDIR /var/local/jekyll
        COPY --chmod=04400 Gemfile Gemfile.lock .
        RUN bundle install 
    command: bundle exec jekyll serve --host 0.0.0.0
    working_dir: "/var/local/jekyll"
    volumes:
      - ".:/var/local/jekyll"
    ports:
      - "4000:4000"
  yamale:
    build:
      context: "."
      dockerfile_inline: |
        FROM python:3.12-bookworm
        RUN adduser --uid 1000 yamale
        RUN python3 -m pip install --user pipx
        RUN python3 -m pipx install --global yamale
    entrypoint: /usr/local/bin/yamale
    user: yamale
    working_dir: "/work"
    command: yamale
    volumes:
      - "${PWD}:/work"
